- name: apt-get update
  apt:
    update_cache: yes

- name: apt-get upgrade
  apt:
    upgrade: full

- name: 必要そうなパッケージをインストールする
  apt:
    pkg:   '{{ item }}'
    state: installed
  with_items:
    - build-essential
    - curl
    - g++
    - git
    - make
